[package]
name = "stippling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.1"
rand = "0.8.5"
image = "0.24.3"
voronoi = "0.1.4"
radsort = "0.1.0"
ordered-float = "3.0.0"